name: biometric_attendance
description: A fingerprint-based attendance system using Flutter and SecuGen.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  image_picker: ^1.1.0
  sqflite: ^2.3.2
  path: ^1.8.3
  timezone: ^0.9.2
  geolocator: ^11.0.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  pdf: ^3.10.7
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpeg
